service: cat-twitter
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-north-1
  memorySize: 256
  timeout: 8
  apiGateway:
    shouldStartNameWithService: true
#  vpc:
#    securityGroupIds:
#      - sg-092de98a98b54ff05
#    subnetIds:
#      - subnet-3d906570
  environment:
#    MONGODB_URL: "mongodb://172.31.1.101"
    SECRET: "mysecret"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueAttributes'
      Resource: "arn:aws:sqs:eu-north-1:182446513661:emailQueue"
    - Effect: "Allow"
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
      Resource: "arn:aws:dynamodb:eu-north-1:182446513661:table/Cat-Users"
    - Effect: "Allow"
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
        - 'dynamodb:DeleteItem'
      Resource: "arn:aws:dynamodb:eu-north-1:182446513661:table/Cat-Posts"
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
