.PHONY: deploy dev

deploy:
	echo 'export const CATTWITTER_HOST="ec2-13-48-126-190.eu-north-1.compute.amazonaws.com"' > src/Config.js \
	&& npm start

dev:
	echo 'export const CATTWITTER_HOST="localhost"' > src/Config.js \
 	&& npm start
