.PHONY: deploy dev

deploy:
	echo 'export const CATTWITTER_HOST="s3-website.eu-north-1.amazonaws.com"' > src/Config.js \
	&& npm start

dev:
	echo 'export const CATTWITTER_HOST="localhost"' > src/Config.js \
 	&& npm start
